guides/loot-filters.md, src/main/java/com/lootfilters/lang/Lexer.java, src/main/java/com/lootfilters/lang/Token.java, src/main/java/com/lootfilters/lang/TokenStream.java, src/test/resources/com/lootfilters/parser-test.rs2f, src/test/resources/com/lootfilters/preprocessor-test-input.rs2f
=> support comments in filter scripts

src/main/java/com/lootfilters/LootFiltersPanel.java
=> fix uncaught exception on saving an invalid filter

src/main/java/com/lootfilters/MatcherConfig.java, src/main/java/com/lootfilters/rule/ValueTier.java, src/main/java/com/lootfilters/util/FilterUtil.java
cc @AndyxWood 
Closes #24 
Closes #28
=> add "none" option for value notify/lootbeam and disable forced value display

src/main/java/com/lootfilters/lang/Preprocessor.java, src/test/resources/com/lootfilters/preprocessor-test-expect.rs2f, src/test/resources/com/lootfilters/preprocessor-test-input.rs2f
=> expand non-parameterized macros

src/main/java/com/lootfilters/DisplayConfig.java, src/main/java/com/lootfilters/LootFiltersConfig.java, src/main/java/com/lootfilters/LootFiltersPlugin.java, src/main/java/com/lootfilters/lang/Parser.java, src/main/java/com/lootfilters/rule/Sound.java
=> loot filters: add sound playback support for item drops

src/main/java/com/lootfilters/LootFiltersOverlay.java, src/main/java/com/lootfilters/util/TextUtil.java
=> use shorthand text for quantity, hide money value

src/main/java/com/lootfilters/LootFiltersOverlay.java, src/main/java/com/lootfilters/LootFiltersPlugin.java, src/main/java/com/lootfilters/LootbeamIndex.java
=> reap tile items from index as map chunks load

src/main/java/com/lootfilters/DisplayConfig.java, src/main/java/com/lootfilters/LootFiltersPlugin.java, src/main/java/com/lootfilters/lang/Parser.java
=> support lootbeam color (defaults to text color)

src/main/java/com/lootfilters/DisplayConfig.java, src/main/java/com/lootfilters/LootFiltersOverlay.java, src/main/java/com/lootfilters/lang/Parser.java, src/main/java/com/lootfilters/rule/FontType.java, src/main/java/com/lootfilters/util/TextComponent.java, src/main/resources/com/lootfilters/scripts/preamble.rs2f
=> support larger font type

src/main/java/com/lootfilters/LootFiltersMouseAdapter.java, src/main/java/com/lootfilters/util/TextUtil.java
=> Adds toggle functionality for left/right click

src/main/java/com/lootfilters/LootFiltersMouseAdapter.java, src/main/java/com/lootfilters/lang/Parser.java, src/main/java/com/lootfilters/rule/ItemTradeableRule.java, src/test/java/com/lootfilters/ParserTest.java, src/test/resources/com/lootfilters/parser-test.rs2f
=> Add the ability to parse on item tradability

src/main/java/com/lootfilters/MenuEntryComposer.java
=> fix bad collapse text when items have same name / diff id

src/main/java/com/lootfilters/DisplayConfig.java, src/main/java/com/lootfilters/MenuEntryComposer.java, src/main/java/com/lootfilters/lang/Parser.java
=> Custom menu text color

src/main/java/com/lootfilters/LootFiltersConfig.java, src/main/java/com/lootfilters/LootFiltersOverlay.java, src/main/java/com/lootfilters/LootFiltersPlugin.java, src/main/java/com/lootfilters/LootbeamIndex.java, src/main/java/com/lootfilters/TileItemIndex.java, src/main/java/com/lootfilters/model/DespawnTimerType.java, src/main/java/com/lootfilters/model/PluginTileItem.java
=> add seconds/pie despawn timers

src/main/java/com/lootfilters/LootFilter.java, src/main/java/com/lootfilters/LootFiltersPanel.java, src/main/java/com/lootfilters/LootFiltersPlugin.java, src/main/java/com/lootfilters/Migrations.java, src/main/java/com/lootfilters/lang/Sources.java, src/main/java/com/lootfilters/rule/ItemTradeableRule.java, src/main/java/com/lootfilters/util/CollectionUtil.java, src/main/java/com/lootfilters/util/TextUtil.java, src/main/resources/com/lootfilters/scripts/filterscape.rs2f, src/main/resources/com/lootfilters/scripts/poeFilter.rs2f
=> Add reference filter: "loot-filters/filterscape"

src/main/resources/com/lootfilters/scripts/filterscape.rs2f
Fixed incorrect name assignment
=> Fix incorrect item name

src/main/java/com/lootfilters/DisplayConfig.java, src/main/java/com/lootfilters/LootFiltersConfig.java, src/main/java/com/lootfilters/LootFiltersPlugin.java, src/main/java/com/lootfilters/lang/Parser.java
=> add drop sound filter config

src/main/java/com/lootfilters/LootFiltersConfig.java, src/main/java/com/lootfilters/LootFiltersOverlay.java, src/main/java/com/lootfilters/LootFiltersPlugin.java, src/main/java/com/lootfilters/LootbeamIndex.java, src/main/java/com/lootfilters/TileItemIndex.java, src/main/java/com/lootfilters/model/DespawnTimerType.java, src/main/java/com/lootfilters/model/PluginTileItem.java
=> add seconds/pie despawn timer

src/main/java/com/lootfilters/lang/Lexer.java, src/main/java/com/lootfilters/lang/Parser.java, src/main/java/com/lootfilters/lang/Token.java, src/main/java/com/lootfilters/rule/NotRule.java, src/test/java/com/lootfilters/ParserTest.java, src/test/resources/com/lootfilters/parser-test.rs2f
See test updates for examples.
Closes #58
=> support unary ! operator around conditions

src/main/java/com/lootfilters/LootFiltersConfig.java, src/main/java/com/lootfilters/LootFiltersOverlay.java, src/main/java/com/lootfilters/LootbeamIndex.java, src/main/java/com/lootfilters/model/DualValueDisplayType.java, src/main/java/com/lootfilters/model/ValueDisplayType.java
=> support more value display options

src/main/java/com/lootfilters/LootFiltersConfig.java, src/main/java/com/lootfilters/LootFiltersMouseAdapter.java, src/main/java/com/lootfilters/LootFiltersOverlay.java, src/main/java/com/lootfilters/LootFiltersPlugin.java
Closes #78 
Closes #67 
This patch also moves the pie version of the despawn timer to the left.
=> add highlight/hide clickboxes

src/main/java/com/lootfilters/DisplayConfig.java, src/main/java/com/lootfilters/LootFiltersConfig.java, src/main/java/com/lootfilters/LootFiltersOverlay.java, src/main/java/com/lootfilters/lang/Parser.java, src/main/java/com/lootfilters/util/FilterUtil.java
Closes #82 
I'm leaving the stroke size alone for now because I dont really want people to be able to configure insane values for it. We can always re-evaluate.
=> add tile highlight config/script

src/main/java/com/lootfilters/lang/TokenStream.java
=> fix TokenStream list arg parsing

src/main/java/com/lootfilters/DisplayConfig.java, src/main/java/com/lootfilters/LootFiltersOverlay.java, src/main/java/com/lootfilters/MatcherConfig.java, src/main/java/com/lootfilters/lang/Parser.java, src/main/java/com/lootfilters/util/FilterUtil.java
=> filter: add hideOverlay control

src/main/java/com/lootfilters/rule/ItemNameRule.java
=> Added support for wildcards at both the start and end of item names

src/main/java/com/lootfilters/lang/Parser.java, src/main/java/com/lootfilters/lang/TokenStream.java, src/main/java/com/lootfilters/rule/ItemIdRule.java
=> support list of ids

src/main/java/com/lootfilters/DisplayConfig.java, src/main/java/com/lootfilters/LootFiltersConfig.java, src/main/java/com/lootfilters/LootFiltersOverlay.java, src/main/java/com/lootfilters/model/FontMode.java, src/main/java/com/lootfilters/rule/FontType.java, src/main/resources/com/lootfilters/scripts/preamble.rs2f
=> add font type mode and bold font

src/main/java/com/lootfilters/DisplayConfig.java, src/main/java/com/lootfilters/LootFilterManager.java, src/main/java/com/lootfilters/LootFiltersConfig.java, src/main/java/com/lootfilters/LootFiltersPanel.java, src/main/java/com/lootfilters/LootFiltersPlugin.java, src/main/java/com/lootfilters/lang/Parser.java, src/main/java/com/lootfilters/util/AudioPlayer.java
=> add drop sounds

src/main/java/com/lootfilters/lang/Preprocessor.java
=> raise preproc exception when arg sizes don't match

src/main/java/com/lootfilters/LootFiltersPlugin.java, src/main/java/com/lootfilters/MenuEntryComposer.java
=> collapse menu on client tick instead of menu open

src/main/java/com/lootfilters/LootFilterManager.java
Adds a chat message indicating how many filters were loaded upon clicking the reload button in the side panel.
=> add reload filter chat message

src/main/java/com/lootfilters/lang/Parser.java, src/main/java/com/lootfilters/rule/ConstRule.java, src/test/java/com/lootfilters/ParserTest.java
=> support const true/false exprs

src/main/java/com/lootfilters/lang/Preprocessor.java, src/test/resources/com/lootfilters/preprocessor-test-expect.rs2f, src/test/resources/com/lootfilters/preprocessor-test-input.rs2f
=> allow blank defines

src/main/java/com/lootfilters/LootFiltersPlugin.java, src/main/java/com/lootfilters/lang/Parser.java, src/main/java/com/lootfilters/model/PluginTileItem.java, src/main/java/com/lootfilters/rule/AreaRule.java
=> add "is in area" support to filters

src/main/java/com/lootfilters/rule/ItemNameRule.java, src/main/java/com/lootfilters/util/TextUtil.java
=> support infix wildcard

src/main/java/com/lootfilters/DisplayConfig.java, src/main/java/com/lootfilters/LootFiltersOverlay.java, src/main/java/com/lootfilters/LootFiltersPlugin.java, src/main/java/com/lootfilters/lang/Parser.java, src/main/java/com/lootfilters/model/BufferedImageProvider.java
=> add icon display

src/main/java/com/lootfilters/LootFiltersPlugin.java
=> fix display not resetting on area filters

src/main/java/com/lootfilters/LootFilterManager.java
This prevents showing the message every time you log in for the first time.
=> don't add loaded filter message unless logged in

src/main/java/com/lootfilters/MenuEntryComposer.java
=> recolor menu entries for telegrab etc.
